server:
  port: 8765

spring:
  profiles:
    default: dev

  mvc:
    view:
      prefix: /resources/templates
      suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 우리는 mysql을 사용한다.
    username: study # DB계정명
    password: 1234 # DB비밀번호
    url: jdbc:mysql://keitian.moe:3306/matchcodetest # 이부분을 localhost로 변경하여 로컬환경에서 테스트할수있다.

  #  data:
  #    mongodb:
  #      host: keitian.moe
  #      port: 27017
  #      username: study
  #      password: 1234
  #      database: connectiontest
  #      authentication-database: admin

  jpa:
    open-in-view: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update # ddl 자동작성여부(update)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
---
server:
  port: 8765

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
---
server:
  port: 9999

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate
